# databasedotcom.yml
---
client_secret: "6124701994660720688"
client_id: "3MVG9QDx8IX8nP5SfDXgDDfBwGBG1ExFGGeZcZi7fdhrj47p6jtKr38QDPSe6R0MFwBLUoqUVJZujDIj4H0sm"
host: test.salesforce.com
username: 312@mohhaiti.org.apptest
password: T00ShortT4KoI12uZgsYTyImD2O4SW5Q
verify_mode: OpenSSL::SSL::VERIFY_NONE