# databasedotcom.yml
---
client_secret: "3428008958368173267"
client_id: "3MVG9QDx8IX8nP5SfDXgDDfBwGP2pLCj4mPtFEDpQocagk1J7TPDfQ_nx1vO.J4fKx9MLgmfSDWRBzCjkc3c_"
host: login.salesforce.com
username: 312@mohhaiti.org
password: 80_yours_trulyQ0YUIB1wS1GbloJTImTldE6V
verify_mode: OpenSSL::SSL::VERIFY_NONE

#312@mohhaiti.org : hope_is_our_mission
