class CreateInterns < ActiveRecord::Migration
  def change
    create_table :interns do |t|
      t.string :firstname
      t.string :lastname
      t.integer :age
      t.datetime :birthday
      t.string :gender
      t.string :termdesired
      t.string :internship_type
      t.string :address
      t.string :city
      t.string :state
      t.string :zip
      t.string :marital_status
      t.integer :how_long_married
      t.string :spouse_name
      t.string :home_phone
      t.string :cell_phone
      t.boolean :can_text
      t.string :best_call_time
      t.string :email
      t.string :tshirt_size
      t.boolean :ever_married
      t.boolean :ever_children
      t.boolean :ever_arrested
      t.boolean :ever_criminal_convicted
      t.text :ever_explainers
      t.text :future_plans
      t.boolean :accepted_Christ
      t.boolean :water_baptized
      t.boolean :attend_church
      t.boolean :church_member
      t.string :home_church
      t.string :denomination
      t.string :church_city
      t.string :church_state
      t.string :church_phone
      t.string :senior_pastor
      t.string :youth_pastor
      t.string :how_long_attended
      t.string :highest_education_level
      t.string :education_other
      t.string :hs_attended
      t.string :hs_city
      t.string :hs_state
      t.boolean :hs_graduate
      t.string :hs_class
      t.string :college
      t.string :major
      t.string :college_city
      t.string :college_state
      t.boolean :college_graduated
      t.string :college_dates_attended
      t.string :other_schools
      t.string :mission_experience
      t.string :mission_city
      t.string :mission_state
      t.boolean :currently_employed
      t.string :current_employer
      t.datetime :ce_hired
      t.string :ce_position
      t.string :ce_city
      t.string :ce_state
      t.string :ce_phone
      t.string :past_employer
      t.string :pe_hired
      t.string :pe_position
      t.string :pe_city
      t.string :pe_state
      t.string :pe_phone
      t.string :father_name
      t.string :father_address
      t.string :father_city
      t.string :father_state
      t.string :father_phone
      t.string :father_work_phone
      t.string :father_occupation
      t.string :father_denomination
      t.boolean :father_accepted_Christ
      t.boolean :father_consent
      t.string :mother_name
      t.string :mother_address
      t.string :mother_city
      t.string :mother_state
      t.string :mother_phone
      t.string :mother_work_phone
      t.string :mother_occupation
      t.string :mother_denomination
      t.boolean :mother_accepted_Christ
      t.boolean :mother_consent
      t.text :siblings
      t.text :parent_feelings
      t.boolean :health_insurance
      t.string :insurance_provider
      t.string :health_description
      t.text :physical_limitation
      t.text :medications
      t.text :drugs
      t.string :emergency_1_name
      t.string :emergency_1_relationship
      t.string :emergency_1_phone
      t.string :emergency_2_name
      t.string :emergency_2_relationship
      t.string :emergency_2_phone
      t.boolean :foreign_language
      t.string :what_languages
      t.string :language_proficiency
      t.boolean :cpr_cert
      t.boolean :firstaid_cert
      t.boolean :other_cert
      t.string :certifications
      t.boolean :child_experience
      t.text :ministry_training
      t.text :tech_training
      t.string :ref1_name
      t.string :ref1_rel
      t.string :ref2_name
      t.string :ref2_rel
      t.string :ref3_name
      t.string :ref3_rel
      t.string :ref4_name
      t.string :ref4_rel
      t.boolean :vbs_experience
      t.boolean :camp_experience
      t.boolean :other_child_experience
      t.boolean :homeless_experience
      t.boolean :senior_experience
      t.boolean :worship_team_experience
      t.boolean :lighting_experience
      t.boolean :photography_experience
      t.boolean :modest_trait
      t.boolean :mature_trait
      t.boolean :kind_trait
      t.boolean :abrasive_trait
      t.boolean :organized_trait
      t.boolean :quiet_trait
      t.boolean :moody_trait
      t.boolean :teachable_trait
      t.boolean :self_motivated_trait
      t.boolean :genuine_trait
      t.boolean :detail_oriented_trait
      t.boolean :loving_trait
      t.boolean :sarcastic_trait
      t.boolean :selfish_trait
      t.boolean :trustworthy_trait
      t.boolean :tactful_trait
      t.boolean :compassionate_trait
      t.boolean :hard_working_trait
      t.boolean :adaptive_trait
      t.boolean :lazy_trait
      t.boolean :punctual_trait
      t.boolean :sensitive_trait
      t.boolean :socially_awkward_trait
      t.boolean :patient_trait
      t.boolean :considerate_trait
      t.boolean :motivated_trait
      t.boolean :impulsive_trait
      t.boolean :relaxed_trait
      t.boolean :friendly_trait
      t.boolean :determined_trait
      t.boolean :leader_trait
      t.text :describe_the_Gospel
      t.text :Christian_experience
      t.text :influential_experiences
      t.text :why_intern
      t.text :why_moh_wants

      t.timestamps
    end
  end
end
